server:
    port: 8080

spring:
    application:
        name: customer
  
    datasource:
        username: customer
        url: jdbc:postgresql://localhost:5432/customer
        password: unidunite
    
    jpa:
        open-in-view: false
        properties:
            hibernate: 
                dialect: org.hibernate.dialect.PostgreSQLDialect
                "[format_sql]": true
        hibernate:
            ddl-auto: update
        show-sql: true