spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/customer
        username: customer
        password: unidunite

    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                "[format_sql]": true
        
        hibernate:
            ddl-auto: update

        show-sql: true
        
        open-in-view: false
