version: '3'

services:

  db:
    container_name: microservice_demo_db
    hostname: pg.microservice
    image: postgres:14-alpine
    environment:
      DATABASE_HOST: '127.0.0.1'
      PGUSER: 'postgres'
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "unidunite"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 
      - ./docker/database:/docker-entrypoint-initdb.d
    networks:
      - postgres 

  pgadmin:
    container_name: microservice_demo_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - postgres


networks:
  postgres:
    driver: bridge